/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.util.ArrayList;
import java.util.List;
import domain.shc_order;
import javax.swing.JOptionPane;

public class Cus_shc_order extends javax.swing.JFrame {

    private ArrayList<shc_order> shclist = new ArrayList<shc_order>();
    public Cus_shc_order() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Sres = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Sfood = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Sdrink = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Sday = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        Shour = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        Sminute = new javax.swing.JComboBox<>();
        Sapm = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        Squan = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Schedule Order");

        jLabel2.setText("Restaurant :");

        Sres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sushi King", "Sakae Sushi", "Nando's", "Hui Lau Shan" }));
        Sres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SresActionPerformed(evt);
            }
        });

        jLabel3.setText("Food           :");

        Sfood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Tamago","Inari","Unagi Slide","Ebi Ten","Golden Ball","Chuka lidako Gunkan","Surimi Scallop","Tuna Mayo","Spider Roll","Kani Tama Maki"}));

        jLabel4.setText("Drink           :");

        Sdrink.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Pepsi","100 plus","Sprite","none"}));

        jLabel5.setText("Step 1 : Select Restaurant");

        jLabel6.setText("Step 2 : Select Food and Drink");

        jLabel7.setText("Step 3 : Select Day and Time");

        jLabel8.setText("Day  :");

        Sday.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday","Tuesday","Wednesday","Thusday","Saturday","Sunday" }));

        jLabel9.setText("Time :");

        Shour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7","8","9","10","11" }));

        jLabel10.setText(":");

        Sminute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00","30" }));

        Sapm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM","PM" }));
        Sapm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SapmActionPerformed(evt);
            }
        });

        jLabel11.setText("Quantity     :");

        Squan.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        jButton1.setText("Comfirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Sday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Sapm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Shour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Sminute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 340, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Sres, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Sfood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Sdrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Squan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Sres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(Sfood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(Sdrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(Squan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Sday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Shour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(Sminute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sapm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SresActionPerformed
        //<editor-fold defaultstate="collapsed" desc=" Select food and drink by different restaurant ">
        
        if(Sres.getSelectedItem().equals("Hui Lau Shan"))
        {
            Sfood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Mango Romance","Mango Triple Delight","Mango Sago","Mango Crystal Jelly","Mango Chewy Ball","D24 Durian Mochi","Mango Pancake","Deluxe Mango Mochi","Watermelon Honey Jelly","Healthy Mango Yakult"}));
            Sdrink.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Pepsi","100 plus","Sprite","none"}));
        }
        else if(Sres.getSelectedItem().equals("Sushi King"))
        {
            Sfood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Tamago","Inari","Unagi Slide","Ebi Ten","Golden Ball","Chuka lidako Gunkan","Surimi Scallop","Tuna Mayo","Spider Roll","Kani Tama Maki"}));
            Sdrink.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Pepsi","100 plus","Sprite","none"}));
        }
        else if(Sres.getSelectedItem().equals("Sakae Sushi"))
        {
            Sfood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Mentai Zukushi","Sachi Set","Salmon Zukushi","Salmon Treasures","Fuku Set","Golden Ball Salmon Trio Mayo","Rainbow Maki","Caterpillar Roll","Jyo Unagi","Ikura"}));
            Sdrink.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Pepsi","100 plus","Sprite","none"}));
        }
        else if(Sres.getSelectedItem().equals("Nando's"))
        {
            Sfood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Chicken Wrap","Chicken Breast Burger","Chicken Caesar Wrap","Chicken Pita","Veggie Burger","Garlic Bread","Chargrilled Veg","Caesar Salad","Red Velvet Cake","Caramel Cheesecake"}));
            Sdrink.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Pepsi","100 plus","Sprite","none"}));
        }
        //</editor-fold>
    }//GEN-LAST:event_SresActionPerformed

    private void SapmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SapmActionPerformed
        // TODO add your handling code here:
        if(Sapm.getSelectedItem().equals("AM"))
        {
            Shour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"7","8","9","10","11"}));
        }
        else if(Sapm.getSelectedItem().equals("PM"))
        {
            Shour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"12","1","2","3","4","5","6","7","8","9"}));
        }
    }//GEN-LAST:event_SapmActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int comfirm;
        
        comfirm = JOptionPane.showConfirmDialog(null,"Are you comfirm your shcdule order??",null,JOptionPane.YES_NO_OPTION);
        
        if(comfirm==JOptionPane.YES_OPTION)
        {
            shc_order shc_order = new shc_order();
            shc_order.setRestaurant(Sres.getSelectedItem().toString());
            shc_order.setFood(Sfood.getSelectedItem().toString());
            shc_order.setDrink(Sdrink.getSelectedItem().toString());
            shc_order.setQuantity(Squan.getComponentCount());
            shc_order.setDay(Sday.getSelectedItem().toString());
            shc_order.setTime(Sapm.getSelectedItem().toString());
            shc_order.setHour(Shour.getSelectedItem().toString());
            shc_order.setMimute(Sminute.getSelectedItem().toString());

            shclist.add(shc_order);            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cus_shc_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cus_shc_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cus_shc_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cus_shc_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cus_shc_order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Sapm;
    private javax.swing.JComboBox<String> Sday;
    private javax.swing.JComboBox<String> Sdrink;
    private javax.swing.JComboBox<String> Sfood;
    private javax.swing.JComboBox<String> Shour;
    private javax.swing.JComboBox<String> Sminute;
    private javax.swing.JSpinner Squan;
    private javax.swing.JComboBox<String> Sres;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
