/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newdeliverman;


import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author JunWeng
 */
public class updatedeliveryman extends javax.swing.JFrame {

    private List<deliverMan> deliverList = new ArrayList<>();
    
    private List<deliverMan> DeliverMan = new ArrayList<>();
  
    public updatedeliveryman() {
        initializeList();
        initComponents();
        this.setTitle("Update Delivery Man's information.");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtfStaffID = new javax.swing.JTextField();
        jtfName = new javax.swing.JTextField();
        jtfIC = new javax.swing.JTextField();
        jtaAddress = new javax.swing.JScrollPane();
        jtfAddress = new javax.swing.JTextArea();
        jtfPhoneNo = new javax.swing.JTextField();
        jtfEmergencyNo = new javax.swing.JTextField();
        jtfEmail = new javax.swing.JTextField();
        jtfGender = new javax.swing.JTextField();
        jcbStatus = new javax.swing.JComboBox<>();
        cancel = new javax.swing.JButton();
        update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Update Delivery Man's profile");

        jLabel2.setText("Search Staff ID");

        jLabel3.setText("Name");

        jLabel4.setText("IC Number");

        jLabel5.setText("Address");

        jLabel6.setText("Phone Number");

        jLabel7.setText("Emergency Contact");

        jLabel8.setText("Email");

        jLabel9.setText("Gender");

        jLabel10.setText("Status");

        jtfStaffID.setMaximumSize(new java.awt.Dimension(400, 30));
        jtfStaffID.setMinimumSize(new java.awt.Dimension(400, 30));
        jtfStaffID.setPreferredSize(new java.awt.Dimension(400, 30));
        jtfStaffID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfStaffIDActionPerformed(evt);
            }
        });

        jtfName.setMaximumSize(new java.awt.Dimension(400, 30));
        jtfName.setMinimumSize(new java.awt.Dimension(400, 30));
        jtfName.setPreferredSize(new java.awt.Dimension(400, 30));

        jtfIC.setMaximumSize(new java.awt.Dimension(400, 30));
        jtfIC.setMinimumSize(new java.awt.Dimension(400, 30));
        jtfIC.setPreferredSize(new java.awt.Dimension(400, 30));

        jtfAddress.setColumns(20);
        jtfAddress.setRows(5);
        jtaAddress.setViewportView(jtfAddress);
        jtfAddress.getAccessibleContext().setAccessibleParent(null);

        jtfPhoneNo.setMaximumSize(new java.awt.Dimension(400, 30));
        jtfPhoneNo.setMinimumSize(new java.awt.Dimension(400, 30));
        jtfPhoneNo.setPreferredSize(new java.awt.Dimension(400, 30));

        jtfEmergencyNo.setMaximumSize(new java.awt.Dimension(400, 30));
        jtfEmergencyNo.setMinimumSize(new java.awt.Dimension(400, 30));
        jtfEmergencyNo.setPreferredSize(new java.awt.Dimension(400, 30));

        jtfEmail.setMaximumSize(new java.awt.Dimension(400, 30));
        jtfEmail.setMinimumSize(new java.awt.Dimension(400, 30));
        jtfEmail.setPreferredSize(new java.awt.Dimension(400, 30));

        jtfGender.setMaximumSize(new java.awt.Dimension(400, 30));
        jtfGender.setMinimumSize(new java.awt.Dimension(400, 30));
        jtfGender.setPreferredSize(new java.awt.Dimension(400, 30));

        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Part-Time", "Full-Time", "Retired", "Quit", "Fired" }));

        cancel.setText("Cancel");

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfStaffID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfIC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtaAddress))
                            .addComponent(jtfEmergencyNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancel)
                                .addGap(109, 109, 109)
                                .addComponent(update)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(99, 99, 99)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel8)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel9)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtaAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfEmergencyNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(update))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfStaffIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfStaffIDActionPerformed
        // TODO add your handling code here:
        int number = (Integer.parseInt(jtfStaffID.getText())-1);
        for(int i = 0 ; i < deliverList.size(); i++)
        {
            if(i == number){
               jtfName.setText(""+deliverList.get(i).getName());
               jtfIC.setText(""+deliverList.get(i).getIC());
               jtfAddress.setText(""+deliverList.get(i).getAddress());
               jtfPhoneNo.setText(""+deliverList.get(i).getContactNo());
               jtfEmergencyNo.setText(""+deliverList.get(i).getEmergencyNo());
               jtfEmail.setText(""+deliverList.get(i).getEmail());
               jtfGender.setText(""+deliverList.get(i).getGender());
               int item = deliverList.get(i).getStatus();
               jcbStatus.setSelectedIndex(item);
            }
        }
    }//GEN-LAST:event_jtfStaffIDActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Delivery Man's information had been updated.");
        String name = jtfName.getText();
        String icNumber = jtfIC.getText();
        String address = jtfAddress.getText();
        String contactNo = jtfPhoneNo.getText();
        String emergencyNo = jtfEmergencyNo.getText();
        String eMail = jtfEmail.getText();
        String gender = jtfGender.getText();
        int status = jcbStatus.getSelectedIndex();
        deliverMan manName = new deliverMan(name,icNumber,address,contactNo,emergencyNo,eMail,gender,status);
        DeliverMan.add(manName);
        //JOptionPane.showMessageDialog(null, "New Delivery Man added.");
        //prepare new staff
        jtfStaffID.setText("" + deliverMan.getDmID());
        jtfName.setText("");
        jtfIC.setText("");
        jtfAddress.setText("");
        jtfPhoneNo.setText("");
        jtfEmergencyNo.setText("");
        jtfEmail.setText("");
        jtfGender.setText("");
        jcbStatus.setSelectedIndex(0);
        jtfName.grabFocus();
         try {
      ObjectOutputStream ooStream = new ObjectOutputStream(new FileOutputStream("DeliveryMan.dat"));
      ooStream.writeObject(DeliverMan);
      //ooStream.close();
      this.dispose();
    } catch (FileNotFoundException ex) {
      JOptionPane.showMessageDialog(null, "File not found", "ERROR", JOptionPane.ERROR_MESSAGE);
    } catch (IOException ex) {
      JOptionPane.showMessageDialog(null, "Cannot save to file", "ERROR", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_updateActionPerformed

      private void initializeList() {
    try{
      ObjectInputStream oiStream = new ObjectInputStream(new FileInputStream("DeliveryMan.dat"));
      deliverList = (ArrayList) (oiStream.readObject());
      oiStream.close();
    } catch (FileNotFoundException ex) {
      JOptionPane.showMessageDialog(null, "File not found", "ERROR", JOptionPane.ERROR_MESSAGE);
    } catch (IOException ex) {
      JOptionPane.showMessageDialog(null, "Cannot read from file", "ERROR", JOptionPane.ERROR_MESSAGE);
    } catch (ClassNotFoundException ex) {
      JOptionPane.showMessageDialog(null, "Class not found", "ERROR", JOptionPane.ERROR_MESSAGE);
    }
  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatedeliveryman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatedeliveryman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatedeliveryman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatedeliveryman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updatedeliveryman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jcbStatus;
    private javax.swing.JScrollPane jtaAddress;
    private javax.swing.JTextArea jtfAddress;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfEmergencyNo;
    private javax.swing.JTextField jtfGender;
    private javax.swing.JTextField jtfIC;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtfPhoneNo;
    private javax.swing.JTextField jtfStaffID;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
