/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agileassignment;

import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class cashPayment extends javax.swing.JFrame {

    /**
     * Creates new form cashPayment
     */
    public cashPayment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RM50Button = new javax.swing.JButton();
        RM100Button = new javax.swing.JButton();
        noChangeNeededButton = new javax.swing.JButton();
        paymentAmtButton = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(355, 300));

        RM50Button.setText("RM 50");
        RM50Button.setMaximumSize(new java.awt.Dimension(133, 23));
        RM50Button.setMinimumSize(new java.awt.Dimension(133, 23));
        RM50Button.setPreferredSize(new java.awt.Dimension(133, 23));
        RM50Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RM50ButtonActionPerformed(evt);
            }
        });

        RM100Button.setText("RM 100");
        RM100Button.setMaximumSize(new java.awt.Dimension(133, 23));
        RM100Button.setMinimumSize(new java.awt.Dimension(133, 23));
        RM100Button.setPreferredSize(new java.awt.Dimension(133, 23));
        RM100Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RM100ButtonActionPerformed(evt);
            }
        });

        noChangeNeededButton.setText("NO CHANGE NEEDED");
        noChangeNeededButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noChangeNeededButtonActionPerformed(evt);
            }
        });

        paymentAmtButton.setText("Please choose your payment amount");

        cancelButton.setText("CANCEL");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(noChangeNeededButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RM100Button, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RM50Button, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paymentAmtButton))
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addGap(136, 136, 136))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(paymentAmtButton)
                .addGap(30, 30, 30)
                .addComponent(RM50Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(RM100Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(noChangeNeededButton)
                .addGap(31, 31, 31)
                .addComponent(cancelButton)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noChangeNeededButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noChangeNeededButtonActionPerformed
        String msg = "Order Completed!";
        String title = "ORDER COMPLETED";
        JOptionPane.showMessageDialog(null, msg, title, JOptionPane.INFORMATION_MESSAGE);
        restaurant rest = new restaurant();
        rest.setVisible(true);
    }//GEN-LAST:event_noChangeNeededButtonActionPerformed

    private void RM50ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RM50ButtonActionPerformed
        String msg = "Order Completed!";
        String title = "ORDER COMPLETED";
        JOptionPane.showMessageDialog(null, msg, title, JOptionPane.INFORMATION_MESSAGE);
        restaurant rest = new restaurant();
        rest.setVisible(true);
    }//GEN-LAST:event_RM50ButtonActionPerformed

    private void RM100ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RM100ButtonActionPerformed
        String msg = "Order Completed!";
        String title = "ORDER COMPLETED";
        JOptionPane.showMessageDialog(null, msg, title, JOptionPane.INFORMATION_MESSAGE);
        restaurant rest = new restaurant();
        rest.setVisible(true);
    }//GEN-LAST:event_RM100ButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        CloseFrame();
    }//GEN-LAST:event_cancelButtonActionPerformed

    public void CloseFrame() {
        super.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cashPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cashPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cashPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cashPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cashPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RM100Button;
    private javax.swing.JButton RM50Button;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton noChangeNeededButton;
    private javax.swing.JLabel paymentAmtButton;
    // End of variables declaration//GEN-END:variables
}
